### PR TITLE
PV horizontal tracking 

### PR DESCRIPTION
**Pull request by Parisra**
## Description
This pull request adds two options for solar tracking, namely 1-axis tracking on a North-South horizontal axis, and 1-axis tracking on a tilted North-South axis.

It also changes the name of 2-axes tracking from 'vh' to the more descriptive 'dual'.

## Motivation and Context
Since vertical tracking and dual tracking have already been added in a previous pull request(https://github.com/PyPSA/atlite/pull/255), horizontal is now added to complete the tracking options, especially since horizontal tracking is more common in reality today.

## How Has This Been Tested?
- The equations have been tested throughly and the results were compared to literature and data from PVGIS (https://re.jrc.ec.europa.eu/pvg_tools/en/tools.html). A comparison between different tracking options is shown in the updated example notebook.
-  the functionality has also been tested .

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] I locally ran `pytest` inside the repository and no unexpected problems came up.
- [ ] I have adjusted the docstrings in the code appropriately.
- [ ] I have documented the effects of my code changes in the documentation `doc/`.
- [ ] I have added newly introduced dependencies to `environment.yaml` file.
- [x] I have added a note to release notes `doc/release_notes.rst`.
- [ ] I have used `pre-commit run --all` to lint/format/check my contribution

### CODE REVIEW

**Comment by Parisra** [comment]
This pull request is an updated version of the older pull request (https://github.com/martavp/atlite/pull/1) that was closed due to conflict created by the addition of example notebook.

**Comment by martavp** [comment]
Great, thanks for implementing the changes indicated in your first pull request. https://github.com/martavp/atlite/pull/1
Thanks again for taking care of this, I have reviewed the new change and I think this is ready to merge with the main repository.

**Comment by martavp** [comment]
I had to correct a small bug
https://github.com/PyPSA/atlite/commit/197d76ad83fa22c6b5d7e8811017049cd94121c2
I mention it here so that you are aware @Parisra

**Comment by Parisra** [comment]
Thanks for the fix, I totally missed it.

**Pull request merged**
